/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'bbq' : IDL.Null,
  'naan_roti' : IDL.Null,
  'fish' : IDL.Null,
  'drinks' : IDL.Null,
  'karahi' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'spiceLevel' : IDL.Opt(IDL.Text),
  'category' : Category,
  'price' : IDL.Opt(IDL.Text),
});
export const RestaurantInfo = IDL.Record({
  'hours' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'bbq' : IDL.Null,
    'naan_roti' : IDL.Null,
    'fish' : IDL.Null,
    'drinks' : IDL.Null,
    'karahi' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'spiceLevel' : IDL.Opt(IDL.Text),
    'category' : Category,
    'price' : IDL.Opt(IDL.Text),
  });
  const RestaurantInfo = IDL.Record({
    'hours' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };